In [1]:
import numpy as np
import plotly.express as px
from sray.dataset.database import ScannetDatabase
import os
from plyfile import PlyData

In [2]:
scene_name = 'scannet/scene0000_00/black_320'
dataset = ScannetDatabase(scene_name)

In [3]:
ROOT = 'data/scannet/scene0000_00/'
filename = os.path.join(ROOT, "scene0000_00_vh_clean_2.ply")
with open(filename, 'rb') as f:
    plydata = PlyData.read(f)
    num_verts = plydata['vertex'].count
    vertices = np.zeros(shape=[num_verts, 6], dtype=np.float32)
    vertices[:, 0] = plydata['vertex'].data['x']
    vertices[:, 1] = plydata['vertex'].data['y']
    vertices[:, 2] = plydata['vertex'].data['z']
    vertices[:, 3] = plydata['vertex'].data['red']
    vertices[:, 4] = plydata['vertex'].data['green']
    vertices[:, 5] = plydata['vertex'].data['blue']


In [4]:
axis_align_matrix = dataset.get_axis_align_matrix()
pts = np.ones((vertices.shape[0], 4))
pts[:, 0:3] = vertices[:, :3]
pts = np.dot(pts, axis_align_matrix.transpose())[:,:3]

In [9]:
aabb_min = np.min(pts,0)
aabb_min

array([-3.63584548, -3.61220749, -0.06493457])

In [10]:
aabb_max = np.max(pts,0)
aabb_max

array([3.40548895, 3.63672   , 2.96044291])

In [7]:
aabb_min + aabb_max

array([-0.23035654,  0.02451251,  2.89550834])

In [8]:
dataset.get_aabb()

array([[-3.63584548, -3.61220749, -0.06493457],
       [ 3.40548895,  3.63672   ,  2.96044291]])